### ISSUE TITLE
[Issue] Mismatched Dates

### ISSUE THREAD

**Issue by Andrew-J-Larson** [kc9eye/GalnetArchive#12]
I finally figured the date issue out.

The API is not wrong, and I confirmed with other 3rd party devs with their recorded rss feeds of the article posts that came out in the past.

Turns out the archive url has indeed accidentally shifted some of the official post dates.

As an example, here's an online 3rd party API that has been going for a long time collecting the articles as they come out with the correct date information for "AISLING DUVAL WEDDING CANCELLED": https://inara.cz/galaxy-galnet/?page=85

The official API matches it's date, but the archive date is incorrect, which is another reason why not to scrape the archive page.

**Comment by Andrew-J-Larson** [comment]
They also have all the older 3300 dated articles. I'm thinking maybe it'd be a better idea to get a download of their archive, as a start, and then use the official [galnet api](https://cms.elitedangerous/api/galnet) to add on new articles.

**Comment by kc9eye** [comment]
The 3300 articles are included, the dates are those given on either the official Galnet page, or corroborated from multiple sources. IMHO, the date of the article is superfluous to it's release order and the release order is correct and corroborated.

**Comment by Andrew-J-Larson** [comment]
@kc9eye I'm talking about dates 3301 and beyond. In the official archive, it has the dates shifted on some.

You can cross check against two user data bases that have been capturing the posts since the beginning:
- https://news.galnet.fr/galnet-news-2/
- https://inara.cz/galaxy-galnet/

**Comment by Andrew-J-Larson** [comment]
They both have the correct dates (as in match up with the official ED galnet API), where https://community.elitedangerous.com/galnet is wrong.
