### ISSUE TITLE
[Question] Any reason for not including the Galnet news from 3300?

### ISSUE THREAD

**Issue by Andrew-J-Larson** [kc9eye/GalnetArchive#4]
https://elite-dangerous.fandom.com/wiki/GalNet#GalNet_Articles_Archive:~:text=3304-,September,December

**Comment by kc9eye** [comment]
Those are not available on the official Galnet site. Reason is unknown.

**Comment by Andrew-J-Larson** [comment]
True, but you could just compile a list of the very oldest ones, and then include them in your archive file, as it wouldn't cause an issue with the archiver.
