### ISSUE TITLE
[Future Feature Request] A version/setting to allow interval checking/updating of archive

### ISSUE THREAD

**Issue by Andrew-J-Larson** [kc9eye/GalnetArchive#9]
Probably would be best to not look into this, until after https://github.com/kc9eye/GalnetArchive/issues/8...

Anyways though, I think it would be nice to have this running on a server and updating itself when there's a new post out. And a good way, at least I find, to check when there is a new post out is seeing if there is any changes to the rss feed at: http://cms.elitedangerous.com/galnet.rss

**Comment by kc9eye** [comment]
Sounds like it would be better to use the afore mentioned API.
